#!/usr/bin/python3

def prime_factors(num):
    for n in range(1, int(num / 2) + 1):
        status = True
        if n < 2:
            status = False
        else:
            for i in range(2, n):
                if n % i == 0:
                    status = False
                    if status:
                        if num % n == 0:
                            second_factor = num // n
                            if second_factor > n:
                                print("{:d}={:d}*{:d}".format(num, second_factor, n))
                            else:
                                print("{:d}={:d}*{:d}".format(num, n, second_factor))
                            break



def factors(file):
    with open(file, "r") as files:
        for i in files:
            i = int(i.strip("\n"))
            prime_factors(i)




if __name__ == "__main__":
    factors("file.txt")
